spring.application.name=confirmation-system
spring.datasource.url=jdbc:mysql://localhost:3306/delivery_confirmation_v2
spring.datasource.username=root
spring.datasource.password=2004#TSK#12#niggahoe
# This is the important part!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true